//傳ACTION防呆頁面
const CartActionTypes = {
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  TOGGLE_CART_SHOW: "TOGGLE_CART_SHOW",
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
  ADD_QUANTITY: "ADD_QUANTITY",
  CLEAR_CART: "CLEAR_CART",
};

export default CartActionTypes;
